"""
自定义错误状态码
"""

ERROR_PARAMETER = 400101
ERROR_VALIDATE = 400102
ERROR_RESOLVE = 404101

ERROR_INNER_SERVICE = 503001

ERROR_TEXT = {
    ERROR_PARAMETER: "参数获取失败",
    ERROR_VALIDATE: "参数验证不合格",
    ERROR_INNER_SERVICE: "内部服务异常",
    ERROR_RESOLVE: "解析失败"
}
